apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advanced-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/standardizing-agility/gitops-cluster-hub.git
    targetRevision: main
    path: advanced-cluster-management
  destination:
    server: https://kubernetes.default.svc
    namespace: open-cluster-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
