apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-serverless
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/standardizing-agility/gitops-cluster-hub.git
    targetRevision: main
    path: openshift-serverless
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
