apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-serverless-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/standardizing-agility/gitops-cluster-hub.git
    targetRevision: main
    path: openshift-serverless-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-serverless
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
