apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - knative-serving-namespace.yaml # sync-wave-0
  - knative-eventing-namespace.yaml # sync-wave-0
  - knative-serving.yaml # sync-wave-1
  - knative-eventing.yaml # sync-wave-2
