apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: cluster-argocd
spec:
  rbac:
    policy: 'g, rbacsystem:cluster-admins, role:admin'
    scopes: '[groups]'
  server:
    route:
      enabled: true
      tls:
        termination: reencrypt
        insecureEdgeTerminationPolicy: Redirect
  sso:
    provider: dex
    dex:
      openShiftOAuth: true